### PR TITLE
Update swinunetr template with mlflow and hyperparameter name. 

### PR DESCRIPTION
**Pull request by heyufan1995**
tests passed.

### CODE REVIEW

**Comment by dongyang0122** [comment]
@heyufan1995 There is metadata.json under auto3dseg folder. You may update that file as well. The rest changes look good to me.

**Comment by dongyang0122** [comment]
Hi @wyli, shall I merge it if I can add the change in metadata.json in my PR? Thanks!

**Review by dongyang0122 — COMMENTED** [review]
mlflow.end_run() is missing after writer.close().

**Comment by myron** [comment]
@heyufan1995  you don't have any mlflow.log_metric calls, I don't think anything is logged

**Comment by dongyang0122** [comment]
Here is an example to add metrics in mlflow logging.
https://github.com/Project-MONAI/research-contributions/blob/main/auto3dseg/algorithm_templates/dints/scripts/train.py#L626

**Comment by heyufan1995** [comment]
@wyli I made changes addressing Dong and Andriy's comments. Passed the tests and added the meta version.

**Pull request merged**
