### PR TITLE
Update ssl_head.py

### PR DESCRIPTION
**Pull request by numanai**
Model name needs to be changed at line 88 to match the change made in the last update at line 23. (Change swin_vit to swinViT)

### CODE REVIEW

**Comment by wyli** [comment]
Could you please review @nvahmadi @tangy5, looks like actually https://github.com/Project-MONAI/research-contributions/pull/89 won't work? There's no integration tests for this repo. Please do download the pr and run the experiments again to confirm code changes if you'd like to provide pr reviews.

**Comment by Mushtaqml** [comment]
The pre-training is running smoothly after making the change.

**Comment by numanai** [comment]
The training is running smoothly after this change.

**Comment by nvahmadi** [comment]
Agreed, this PR should fix this issue, was a copy&paste error from the previous PR, I missed that line. Apologies for that mistake, and thanks @numanai for the quick fix!

**Pull request merged**
