### PR TITLE
Auto3DSeg CT Transforms and SwinUNETR fix

### PR DESCRIPTION
**Pull request by mingxin-zheng**
There are repeated issues reported on the CT-related transforms in the Auto3DSeg pipeline. This PR is trying to address them with fixes and new test to cover the CT cases.

To-do:
- [x] Write parameterized test case to cover different Auto3DSeg configurations 
- [ ] Fix templates 

Issue Ref: 
https://github.com/Project-MONAI/tutorials/issues/965
https://github.com/Project-MONAI/MONAI/issues/5226

### CODE REVIEW

**Comment by mingxin-zheng** [comment]
@tangy5 To fix the Spacingd for Task05_Prostate, whose image has the dimension of (320, 320, 15, 2), I implemented something in the algo.py as below to ensure spacing is adjustable for this and other special cases.

```python
min_shape = data_stats["stats_summary#image_stats#shape#min"]
spacing = [min(s / 24, spacing[i]) for i, s in enumerate(min_shape)]
...
transforms_train.update({'transforms_train#transforms#3#pixdim': spacing})
```

Also, in CT cases, there is a `CropForegroundd` transform for all networks. But for SwinUNETR, the `CropForegroundd` may make the ROI smaller than the minimum required patch size (64, 64, 64) . How much impact would it be if I remove it?

**Comment by tangy5** [comment]
> @tangy5 To fix the Spacingd for Task05_Prostate（dimension is (320, 320, 15, 2) and modality is MRI), I implemented something in the algo.py as below to ensure spacing is adjustable for this and other special cases.
> 
> ```python
> min_shape = data_stats["stats_summary#image_stats#shape#min"]
> spacing = [min(s / 24, spacing[i]) for i, s in enumerate(min_shape)]
> ...
> transforms_train.update({'transforms_train#transforms#3#pixdim': spacing})
> ```
> 
> Also, in CT cases, there is a `CropForegroundd` transform for all networks. But for SwinUNETR, the `CropForegroundd` may make the ROI smaller than the minimum required patch size (64, 64, 64) . How much impact would it be if I remove it?

HI @mingxin-zheng , thanks for handling this. I agree there should be a robust spacing when comes to small image dimension size, how is the s/24 is decided here?

About CT, there should be no issues with **CropForegroundd** as I tested. CT images are larger dimension, and cropping/padding can guarantee the dimension requirement.

**Comment by tangy5** [comment]
> > @tangy5 To fix the Spacingd for Task05_Prostate（dimension is (320, 320, 15, 2) and modality is MRI), I implemented something in the algo.py as below to ensure spacing is adjustable for this and other special cases.
> > ```python
> > min_shape = data_stats["stats_summary#image_stats#shape#min"]
> > spacing = [min(s / 24, spacing[i]) for i, s in enumerate(min_shape)]
> > ...
> > transforms_train.update({'transforms_train#transforms#3#pixdim': spacing})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, in CT cases, there is a `CropForegroundd` transform for all networks. But for SwinUNETR, the `CropForegroundd` may make the ROI smaller than the minimum required patch size (64, 64, 64) . How much impact would it be if I remove it?
> 
> HI @mingxin-zheng , thanks for handling this. I agree there should be a robust spacing when comes to small image dimension size with MRI, such as Task04 and Task05 in MSD, how is the s/24 is decided here?
> 
> About CT, there should be no issues with **CropForegroundd** as I tested. CT images are larger dimension, and cropping/padding can guarantee the dimension requirement.

**Comment by mingxin-zheng** [comment]
Hi @tangy5 , the 24 was determined by experiments initially. After some debugging, the accurate number should be 
```
int(patch_size[i]/3) + 1
```
for each dimension `i`

The SpatialPadd uses the `reflection` mode with [this PyTorch backend](https://pytorch.org/docs/stable/generated/torch.nn.ReflectionPad2d.html#torch.nn.ReflectionPad2d). For a given patch size (64), the image needs to be at least 22, so the reflected paddings on both sides can fill up the patch (22+22+22 > 64).

**Comment by tangy5** [comment]
> Hi @tangy5 , the 24 was determined by experiments initially. After some debugging, the accurate number should be
> 
> ```
> int(patch_size[i]/3) + 1
> ```
> 
> for each dimension `i`
> 
> The SpatialPadd uses the `reflection` mode with [this PyTorch backend](https://pytorch.org/docs/stable/generated/torch.nn.ReflectionPad2d.html#torch.nn.ReflectionPad2d). For a given patch size (64), the image needs to be at least 22, so the reflected paddings on both sides can fill up the patch (22+22+22 > 64).

Sounds good, thanks.

**Review by tangy5 — APPROVED** [review]

**Comment by mingxin-zheng** [comment]
> About CT, there should be no issues with **CropForegroundd** as I tested. CT images are larger dimension, and cropping/padding can guarantee the dimension requirement.

Hi @tangy5 , thanks for reviewing the change on the first item. On the second item as I quoted, here is a script that proves `CropForegroundd` may go wrong with small targets. 

Here I simulate small circular objects (radius 1~2 pixel) in (32, 32, 32) image and apply **SwinUNETR** predefined transforms. At least on my machine, I ran it repeatedly and would be able to trigger the error in about 10 runs. My understanding is that there is no assurance in`CropForegroundd` to output an image with a given size. By any chance that the target is smaller than what's required by the reflection spatial padding, it will be an error.

<details><summary>CLICK ME to see the testing code</summary>
<p>

```python
import os

import nibabel as nib
import numpy as np
import torch

from monai.auto3dseg import datafold_read
from monai.bundle.config_parser import ConfigParser
from monai.data import create_test_image_3d, CacheDataset

from monai.transforms import Compose, LoadImaged, EnsureChannelFirstd, Orientationd, EnsureTyped, Spacingd, ScaleIntensityRanged, CropForegroundd, CastToTyped, SpatialPadd,

sim_datalist = {
    "training": [
        {"fold": 0, "image": "01.nii.gz", "label": "01.nii.gz"},
        {"fold": 0, "image": "02.nii.gz", "label": "02.nii.gz"},
        {"fold": 0, "image": "03.nii.gz", "label": "03.nii.gz"},
        {"fold": 0, "image": "04.nii.gz", "label": "04.nii.gz"},
        {"fold": 1, "image": "05.nii.gz", "label": "05.nii.gz"},
        {"fold": 1, "image": "06.nii.gz", "label": "06.nii.gz"},
        {"fold": 1, "image": "07.nii.gz", "label": "07.nii.gz"},
        {"fold": 1, "image": "08.nii.gz", "label": "08.nii.gz"},
        {"fold": 2, "image": "09.nii.gz", "label": "09.nii.gz"},
        {"fold": 2, "image": "10.nii.gz", "label": "10.nii.gz"},
        {"fold": 2, "image": "11.nii.gz", "label": "11.nii.gz"},
        {"fold": 2, "image": "12.nii.gz", "label": "12.nii.gz"},
    ],
}

def create_sim_data(dataroot, sim_datalist, sim_dim, **kwargs):
    """Generate a fake dataset"""
    if not os.path.isdir(dataroot):
        os.makedirs(dataroot)
    
    for d in sim_datalist["testing"] + sim_datalist["training"]:
        im, seg = create_test_image_3d(sim_dim[0], sim_dim[1], sim_dim[2], **kwargs)
        image_fpath = os.path.join(dataroot, d["image"])
        label_fpath = os.path.join(dataroot, d["label"])
        nib_im = nib.Nifti1Image(im, affine=np.eye(4))
        nib_seg = nib.Nifti1Image(seg, affine=np.eye(4))
        nib.save(nib_im, image_fpath)
        nib.save(nib_seg, label_fpath)

dataroot_dir = os.path.join(".", "sim_dataroot")

# Testing conditions
sim_dim = (32, 32, 32)

create_sim_data(dataroot_dir, sim_datalist, sim_dim, rad_max=2, rad_min=1, num_seg_classes=1)

files, _ = datafold_read(datalist=sim_datalist, basedir=dataroot_dir, fold=-1)

transform_list = Compose([
    LoadImaged(keys =("image", "label")),
    EnsureChannelFirstd(keys =("image", "label")),  # this creates label to be (1,H,W,D)
    Orientationd(keys =("image", "label"), axcodes="RAS"),
    Spacingd(keys =("image", "label"), pixdim=(1.0, 1.0, 1.0), mode=("bilinear", "nearest"), align_corners=[True, True]),
    CastToTyped(keys="image", dtype=torch.float32),
    ScaleIntensityRanged(keys="image", a_min=0.0, a_max=1.0, b_min=0.0, b_max=1.0),
    CropForegroundd(keys="image", source_key="image"),
    EnsureTyped(keys =("image", "label")),
    SpatialPadd(keys =("image", "label"), mode=("reflect", "constant"), spatial_size=(64, 64, 64))
])

dataset = CacheDataset(data=files, transform=transform_list, cache_rate=1/4.0, num_workers=4, progress=False)
```

</p>
</details>

Error:
```bash
(base) root@adminn-MS-7D31:/workspace/monai/monai-in-dev# python test_spatial_padd.py
(base) root@adminn-MS-7D31:/workspace/monai/monai-in-dev# python test_spatial_padd.py
(base) root@adminn-MS-7D31:/workspace/monai/monai-in-dev# python test_spatial_padd.py
(base) root@adminn-MS-7D31:/workspace/monai/monai-in-dev# python test_spatial_padd.py
(base) root@adminn-MS-7D31:/workspace/monai/monai-in-dev# python test_spatial_padd.py
(base) root@adminn-MS-7D31:/workspace/monai/monai-in-dev# python test_spatial_padd.py
Traceback (most recent call last):
  File "/workspace/monai/monai-in-dev/monai/transforms/croppad/array.py", line 184, in __call__
    out = _pad(img_t, pad_width=to_pad_, mode=mode_, **kwargs_)
  File "/workspace/monai/monai-in-dev/monai/transforms/croppad/array.py", line 138, in _pt_pad
    return pad_pt(img.unsqueeze(0), pt_pad_width, mode=mode, **kwargs).squeeze(0)
  File "/workspace/monai/monai-in-dev/monai/data/meta_tensor.py", line 249, in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 1089, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (21, 22) at dimension 4 of input [1, 1, 29, 25, 21]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/monai/monai-in-dev/monai/transforms/transform.py", line 91, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/workspace/monai/monai-in-dev/monai/transforms/transform.py", line 55, in _apply_transform
    return transform(parameters)
  File "/workspace/monai/monai-in-dev/monai/transforms/croppad/dictionary.py", line 147, in __call__
    d[key] = self.padder(d[key], mode=m)
  File "/workspace/monai/monai-in-dev/monai/transforms/croppad/array.py", line 189, in __call__
    raise ValueError(f"{mode_}, {kwargs_}, {img_t.dtype}, {img_t.device}") from err
ValueError: reflect, {}, torch.float32, cpu

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_spatial_padd.py", line 97, in <module>
    dataset = CacheDataset( 
  File "/workspace/monai/monai-in-dev/monai/data/dataset.py", line 794, in __init__
    self.set_data(data)
  File "/workspace/monai/monai-in-dev/monai/data/dataset.py", line 819, in set_data
    self._cache = _compute_cache()
  File "/workspace/monai/monai-in-dev/monai/data/dataset.py", line 808, in _compute_cache
    return self._fill_cache()
  File "/workspace/monai/monai-in-dev/monai/data/dataset.py", line 835, in _fill_cache
    return list(p.imap(self._load_cache_item, range(self.cache_num)))
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/workspace/monai/monai-in-dev/monai/data/dataset.py", line 848, in _load_cache_item
    item = apply_transform(_xform, item)
  File "/workspace/monai/monai-in-dev/monai/transforms/transform.py", line 118, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.croppad.dictionary.SpatialPadd object at 0x7f6acc31fc40>
```

**Pull request merged**
